artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rushin236/Datasets/raw/main/Phone_Recommendation_System/gsmarena_product_data_final_text.csv
  local_data_file: artifacts/data_ingestion/raw_data.csv

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["raw_data.csv"]

eda:
  root_dir: artifacts/eda
  local_data_file: artifacts/data_ingestion/raw_data.csv
  STATUS_FILE_PATH: artifacts/eda/status.txt
