artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rushin236/Datasets/raw/main/Phone_Recommendation_System/gsmarena_product_data_final_text1.csv
  local_data_file: artifacts/data_ingestion/raw_data.csv

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["raw_data.csv"]

data_extraction:
  root_dir: artifacts/data_extraction
  local_data_file: artifacts/data_ingestion/raw_data.csv
  extracted_data_file: artifacts/data_extraction/extracted_data.csv

data_transform:
  root_dir: artifacts/data_transform
  extracted_data_file: artifacts/data_extraction/extracted_data.csv
  transform_data_file: artifacts/data_transform/transform_data.csv
  vectorizer_file: artifacts/data_transform/vectorizer.pkl

model_training:
  root_dir: artifacts/model_training
  model_file: artifacts/model_training/model.h5
  tokenizer_file: artifacts/model_training/tokenizer.pkl
  transform_data_file: artifacts/data_transform/transform_data.csv
  model_evaluation_file: artifacts/model_training/model_evaluation.txt

prediction:
  model_file: artifacts/model_training/model.h5
  tokenizer_file: artifacts/model_training/tokenizer.pkl
  vectorizer_file: artifacts/data_transform/vectorizer.pkl
  transform_data_file: artifacts/data_transform/transform_data.csv
  max_sequence_length: 50
